import rclpy
from rclpy.node import Node
from interfaces.msg import ActionPlan # Assuming a custom ActionPlan message

class ActionValidator(Node):
    """
    A node that subscribes to a proposed action plan, validates it against
    a set of safety and feasibility rules, and, if valid, publishes it to
    a topic for execution. This acts as a crucial safety layer between the
    LLM and the robot's hardware.
    """
    def __init__(self):
        super().__init__('action_validator')
        self.get_logger().info('Action Validator node started.')
        
        # This is the set of actions the robot is physically capable of.
        self.known_actions = {
            "navigate",
            "grasp",
            "place",
            "say"
        }
        
        # Subscriber to the plan generated by the LLM
        self.subscription = self.create_subscription(
            ActionPlan,
            '/action_plan',
            self.plan_callback,
            10)
            
        # Publisher for the validated plan
        self.publisher = self.create_publisher(
            ActionPlan,
            '/validated_action_plan',
            10)

    def plan_callback(self, msg):
        """
        Callback for validating an incoming action plan.
        """
        self.get_logger().info('Received a plan to validate.')
        
        is_valid = True
        for i, action in enumerate(msg.steps):
            # Rule 1: Is the action known?
            if action.name not in self.known_actions:
                self.get_logger().error(f"Validation failed: Unknown action '{action.name}' at step {i}.")
                is_valid = False
                break
                
            # Rule 2: Are the parameters plausible? (Simple version)
            # A real validator would have much more complex checks.
            if action.name == "navigate":
                if not self.is_location_known(action.parameters.get("location")):
                    self.get_logger().error(f"Validation failed: Unknown location '{action.parameters.get('location')}'")
                    is_valid = False
                    break
            
            if action.name == "grasp":
                if "stove" in action.parameters.get("object_name", ""):
                    self.get_logger().error("Validation failed: Robot is not allowed to grasp the stove.")
                    is_valid = False
                    break

        if is_valid:
            self.get_logger().info('Plan is valid. Publishing to execution topic.')
            self.publisher.publish(msg)
        else:
            self.get_logger().error('Plan is invalid. Dropping plan.')

    def is_location_known(self, location):
        """
        A placeholder for checking against a map or known locations.
        """
        known_locations = ["kitchen", "living_room", "user", "table"]
        return location in known_locations

def main(args=None):
    rclpy.init(args=args)
    action_validator = ActionValidator()
    rclpy.spin(action_validator)
    action_validator.destroy_node()
    rclpy.shutdown()

if __name__ == '__main__':
    main()
